In [ ]:
# We use numpy array beacuase it helps to perform operation easily

In [7]:
# to create and print array
import numpy as np
a= np.array([1,2,3])
print(a)

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
# To know the type
print(type(a))

<class 'numpy.ndarray'>


In [9]:
# To get the shape of array as rows and column
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a.shape)

(3, 3)


In [10]:
print(a.size)

9


In [12]:
# dimesnsion of array
print(a.ndim)

2


In [16]:
# provide the size of each element of array
print(a.itemsize)

8


In [20]:
# to access the actual element of data 
print(a.data)   # (but it doesn't shows the acutal element of the data, I dont unndrstand this)

In [18]:
# basic numpy arthimetic operations
a=np.array([1,2,3])
b=np.array([4,5,6])
c= a+b
print(c)
d= a-b
print(d)
e=a*b
print(e)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [28]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [30]:
a=np.arange(18).reshape(2,9)
print(a)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


In [31]:
a.shape

(2, 9)